version: '3.8'

services:

  front:
    build: ./front
    ports:
      - "8080:8080"

  database:
    build: ./database
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  ml:
    build: ./ml
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8002:8002"

  mongodb:
    image: mongo
    ports:
      - "8001:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: