name: xakaton
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  logger: ^2.2.0
  provider: ^6.1.2
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  flutter_dropzone: ^4.0.0
  file_saver: ^0.2.12
  file_picker: ^8.0.2
  cupertino_icons: ^1.0.8
  vs_scrollbar: ^1.0.0
  pretty_dio_logger: ^1.3.1
  percent_indicator: ^4.0.1
  d_chart: ^2.6.9
  custom_rating_bar: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true


